ALL_NAMES = [
    "James", "Mary", "John", "Patricia", "Robert", "Jennifer", "Michael", "Linda", 
    "William", "Elizabeth", "David", "Barbara", "Richard", "Susan", "Joseph", "Jessica", 
    "Thomas", "Sarah", "Charles", "Karen", "Christopher", "Nancy", "Daniel", "Margaret", 
    "Matthew", "Lisa", "Anthony", "Betty", "Mark", "Dorothy", "Donald", "Sandra", 
    "Steven", "Ashley", "Paul", "Kimberly", "Andrew", "Emily", "Joshua", "Donna", 
    "Kenneth", "Michelle", "Kevin", "Carol", "Brian", "Amanda", "George", "Melissa", 
    "Edward", "Deborah", "Ronald", "Stephanie", "Timothy", "Rebecca", "Jason", "Sharon", 
    "Jeffrey", "Laura", "Ryan", "Cynthia", "Jacob", "Kathleen", "Gary", "Amy", 
    "Nicholas", "Shirley", "Eric", "Angela", "Jonathan", "Helen", "Stephen", "Anna", 
    "Larry", "Brenda", "Justin", "Pamela", "Scott", "Nicole", "Brandon", "Emma", 
    "Frank", "Samantha", "Benjamin", "Katherine", "Gregory", "Christine", "Raymond", "Debra", 
    "Samuel", "Rachel", "Patrick", "Catherine", "Alexander", "Carolyn", "Jack", "Janet", 
    "Dennis", "Ruth", "Jerry", "Maria", "Tyler", "Heather", "Aaron", "Diane", 
    "Henry", "Virginia", "Douglas", "Julie", "Peter", "Joyce", "Adam", "Victoria", 
    "Nathan", "Olivia", "Zachary", "Kelly", "Walter", "Christina", "Kyle", "Lauren", 
    "Harold", "Joan", "Carl", "Evelyn", "Arthur", "Judith", "Gerald", "Megan", 
    "Roger", "Cheryl", "Keith", "Andrea", "Jeremy", "Hannah", "Terry", "Martha", 
    "Lawrence", "Jacqueline", "Sean", "Frances", "Christian", "Gloria", "Albert", "Ann", 
    "Joe", "Teresa", "Ethan", "Kathryn", "Austin", "Sara", "Jesse", "Janice", 
    "Willie", "Jean", "Billy", "Alice", "Bryan", "Madison", "Bruce", "Doris", 
    "Jordan", "Abigail", "Ralph", "Julia", "Roy", "Judy", "Noah", "Grace", 
    "Dylan", "Denise", "Eugene", "Amber", "Wayne", "Marilyn", "Alan", "Beverly", 
    "Juan", "Danielle", "Louis", "Theresa", "Russell", "Sophia", "Gabriel", "Marie", 
    "Randy", "Diana", "Philip", "Brittany", "Harry", "Natalie", "Vincent", "Isabella", 
    "Bobby", "Charlotte", "Johnny", "Rose", "Logan", "Alexis", "Howard", "Kayla", 
    "Martin", "Louis", "Ernest", "Lillian", "Anthony", "Addison", "Fred", "Nora",
]

PERSONAS = [
    "A middle-aged woman with short, curly red hair and a warm smile, who loves baking and often brings cookies to her coworkers.",
    "A tall man in his early twenties, wearing a hoodie and glasses, who always has a book in his hand and spends hours at the local library.",
    "A young girl with pigtails and a mischievous grin, who enjoys climbing trees and exploring the neighborhood with her friends.",
    "An elderly gentleman with a cane and a neatly trimmed white beard, who takes daily walks in the park and feeds the birds.",
    "A teenager with a skateboard and headphones, dressed in ripped jeans and a band t-shirt, who dreams of becoming a famous musician.",
    "A professional woman in her thirties, with straight black hair and a sharp business suit, who is always on her phone managing her successful career.",
    "A little boy with a big, toothy smile, wearing a superhero costume and pretending to save the world in his backyard.",
    "A bearded man in his fifties, wearing a cowboy hat and boots, who loves telling stories about his adventures as a young rancher.",
    "A college student with dyed blue hair and multiple piercings, who is passionate about environmental activism and often organizes campus protests.",
    "A retired schoolteacher with glasses and a gentle demeanor, who volunteers at the local community center helping children with their homework.",
    "A young mother with long blonde hair, pushing a stroller and talking softly to her baby as she walks through the park.",
    "A businessman in his forties, with a neatly trimmed beard and a sharp suit, who spends his evenings reading financial reports.",
    "A teenage boy with a camera, always looking for the perfect shot to capture his next great photograph.",
    "An elderly woman with a knitting bag, sitting on her porch and making scarves for her grandchildren.",
    "A young man with tattoos and a leather jacket, who rides a motorcycle and works as a mechanic.",
    "A little girl with braids and a pink dress, who loves playing with her dolls and having tea parties.",
    "A middle-aged man with a potbelly and a jovial laugh, who enjoys telling jokes and making people smile.",
    "A woman in her late twenties with a serious expression, always seen working on her laptop at the coffee shop.",
    "A grandfather with a walking stick and a twinkle in his eye, who loves sharing stories from his youth.",
    "A high school girl with braces and glasses, who is the star of the school's debate team.",
    "A young boy with curly hair and a big grin, who spends his days playing soccer with his friends.",
    "A middle-aged man with a bald head and a kind face, who volunteers at the local animal shelter.",
    "A teenage girl with a passion for fashion, who spends hours designing and sewing her own clothes.",
    "A young man with a skateboard and a carefree attitude, who loves performing tricks at the local skate park.",
    "An elderly woman with a garden full of flowers, who spends her days tending to her plants and chatting with neighbors.",
    "A man in his thirties with a fit physique, who runs marathons and follows a strict fitness regimen.",
    "A woman in her fifties with a warm smile and an apron, who owns a small bakery and knows all her customers by name.",
    "A little boy with messy hair and a toy car, who loves racing around the living room making engine noises.",
    "A young woman with a backpack and hiking boots, who spends her weekends exploring nature trails and camping.",
    "A man in his forties with a briefcase and a stern look, who is a successful lawyer known for his courtroom prowess.",
    "A teenage girl with long black hair and a sketchbook, who loves drawing and dreams of becoming an artist.",
    "A young boy with a fishing pole, who spends his afternoons by the lake hoping to catch the big one.",
    "An elderly man with a monocle and a cane, who enjoys reading historical novels in his cozy armchair.",
    "A woman in her late twenties with a guitar, who performs at local cafes and writes her own songs.",
    "A young man with a beard and a beanie, who works at a tech startup and loves coding.",
    "A middle-aged woman with a green thumb, who has a house filled with plants and a beautiful garden.",
    "A teenage boy with a love for video games, who streams his gameplay online for his followers.",
    "An elderly woman with a love for puzzles, who spends her afternoons completing intricate jigsaw puzzles.",
    "A young girl with a big imagination, who loves dressing up as different characters and putting on plays.",
    "A man in his fifties with a deep voice and a passion for radio, who hosts a popular local talk show.",
    "A woman in her forties with a love for travel, who has visited over thirty countries and always has a new story to tell.",
    "A little girl with a fascination for insects, who spends hours in the garden looking for bugs and studying them.",
    "A young man with a passion for cooking, who dreams of becoming a renowned chef and owns a food blog.",
    "An elderly gentleman with a collection of vintage cars, who loves attending car shows and sharing his knowledge.",
    "A teenage girl with a love for science, who spends her free time conducting experiments and reading about space.",
    "A middle-aged man with a love for fishing, who wakes up early every weekend to go to his favorite fishing spot.",
    "A woman in her thirties with a flair for interior design, who is always redecorating her home and helping friends with their spaces.",
    "A young boy with a love for dinosaurs, who knows all their names and dreams of becoming a paleontologist.",
    "An elderly woman with a passion for knitting, who makes blankets and scarves for charity.",
    "A teenage boy with a talent for playing the piano, who practices every day and dreams of performing on stage.",
    "A young woman with a love for photography, who captures beautiful moments and landscapes with her camera.",
    "A man in his forties with a love for history, who spends his weekends visiting museums and historical sites.",
    "A little girl with a love for painting, who creates colorful masterpieces and hangs them all over the house.",
    "A woman in her fifties with a passion for gardening, who has a beautiful garden and a green thumb.",
    "A young man with a talent for singing, who performs at local bars and dreams of making it big.",
    "A teenage girl with a love for animals, who volunteers at the local animal shelter and hopes to become a veterinarian.",
    "An elderly man with a love for woodworking, who creates beautiful furniture and gifts for his family.",
    "A young boy with a love for robots, who builds them from kits and dreams of becoming an engineer.",
    "A woman in her thirties with a love for yoga, who teaches classes and practices every day.",
    "A man in his twenties with a love for adventure, who travels to remote places and loves extreme sports.",
    "A little girl with a love for ballet, who practices her moves every day and dreams of becoming a ballerina.",
    "A teenage boy with a talent for drawing, who creates comic books and hopes to become a professional illustrator.",
    "A young woman with a love for literature, who is always seen with a book and dreams of becoming a writer.",
    "A man in his fifties with a love for cooking, who hosts dinner parties and is known for his delicious meals.",
    "A teenage girl with a passion for dance, who practices every day and dreams of joining a professional dance troupe.",
    "A young boy with a love for space, who spends his nights looking at the stars and dreams of becoming an astronaut.",
    "An elderly woman with a love for quilting, who makes beautiful quilts for her family and friends.",
    "A man in his forties with a love for photography, who captures stunning images of nature and landscapes.",
    "A woman in her twenties with a passion for fitness, who is a personal trainer and loves helping others reach their fitness goals.",
    "A teenage boy with a love for chess, who competes in tournaments and dreams of becoming a grandmaster.",
    "A young girl with a love for animals, who has a pet hamster and dreams of having a farm one day.",
    "An elderly gentleman with a love for classical music, who attends concerts and plays the violin.",
    "A woman in her thirties with a passion for painting, who creates beautiful landscapes and portraits.",
    "A young man with a love for surfing, who spends his days at the beach catching waves.",
    "A teenage girl with a love for fashion, who dreams of becoming a designer and often creates her own clothes.",
    "A middle-aged man with a passion for bird watching, who spends his weekends in nature spotting different bird species.",
    "A young woman with a love for baking, who creates delicious cakes and pastries and dreams of opening her own bakery.",
    "A teenage boy with a love for gaming, who streams his gameplay online and has a large following.",
    "A little girl with a love for fairytales, who dresses up as her favorite characters and puts on plays for her family.",
    "A man in his thirties with a love for hiking, who explores different trails and enjoys being in nature.",
    "A woman in her forties with a passion for photography, who captures beautiful moments and landscapes.",
    "A young boy with a love for dinosaurs, who knows all their names and dreams of becoming a paleontologist.",
    "An elderly woman with a passion for knitting, who makes blankets and scarves for charity.",
     "A teenage boy with a skateboard and a love for adventure, always searching for the next big trick.",
    "A cheerful barista with tattoos and a love for latte art, who remembers every regular customer's name.",
    "A quiet young woman in her thirties, who wears headphones and spends her evenings sketching in cafes.",
    "A retired schoolteacher with thick glasses and a collection of vintage maps, who volunteers at the local library.",
    "A child with a colorful backpack and an insatiable curiosity, asking questions about everything they see.",
    "A tall woman with an elegant posture and a tailored suit, who speaks three languages fluently.",
    "An energetic fitness instructor with a ponytail and an infectious enthusiasm for early-morning classes.",
    "A man in his sixties who wears a fedora and plays jazz on his saxophone at street corners.",
    "A college student with headphones and a skateboard, rushing between classes with coffee in hand.",
    "A shy florist in her late twenties who spends hours arranging bouquets to perfection.",
    "A charismatic magician with a top hat and a mischievous twinkle in his eye, performing for kids at parties.",
    "A middle-aged chef with a mustache and a love for classic French cuisine, who dreams of opening his own restaurant.",
    "An aspiring actor in his twenties who works part-time as a waiter while memorizing scripts between shifts.",
    "A retired navy veteran who enjoys fixing up old boats and sailing during the summer.",
    "A baker in her early forties with flour-dusted hands and a passion for experimenting with bread recipes.",
    "A teenager who loves video games and coding, constantly staying up late to work on personal projects.",
    "An elderly woman who knits sweaters for her grandchildren and watches old black-and-white movies.",
    "A fireman with a determined gaze and a dog who follows him everywhere.",
    "A woman in her thirties with a camera slung around her neck, traveling the world to capture unique landscapes.",
    "A young man who collects sneakers and proudly displays them in his meticulously organized bedroom.",
    "A yoga teacher who spends weekends hiking and meditating in the mountains.",
    "A teenage girl who writes poetry in her diary and dreams of publishing her own book someday.",
    "A tech entrepreneur with a coffee addiction and a tendency to pace while brainstorming.",
    "A grandmother who runs a bed-and-breakfast, cooking homemade meals for guests every morning.",
    "An auto mechanic who loves classic cars and hosts garage workshops for local teenagers.",
    "A beekeeper with a wide-brimmed hat and a fascination for honeybees and their colonies.",
    "A bar owner in his fifties who tells tall tales to customers over pints of beer.",
    "A freelance artist who paints murals on city walls and loves experimenting with bold colors.",
    "A fashion student who designs clothes inspired by vintage trends and thrift store finds.",
    "A scientist with frizzy hair and an excited demeanor, always scribbling notes in her lab coat.",
    "A fisherman who wakes up before dawn to head out on his boat and watch the sunrise over the water.",
    "A dog walker in their twenties with a belt full of treats and leashes for their furry clients.",
    "A wedding planner with a love for detail and a notebook filled with elegant sketches and ideas.",
    "A tour guide with a loud voice and a passion for sharing historical anecdotes with visitors.",
    "A young man with a backpack and a camera, couch-surfing his way across Europe on a shoestring budget.",
    "A retired actress who teaches theater to high school students and tells stories of her stage days.",
    "A teenager who loves astronomy and spends nights staring at constellations with their telescope.",
    "A piano teacher with a soft voice and a love for classical music, guiding students with patience.",
    "A chef who specializes in street food, setting up a vibrant food truck at festivals and fairs.",
    "A blacksmith with calloused hands and a fascination for medieval craftsmanship.",
    "A woman with a love for plants, who has turned her apartment into a lush indoor jungle.",
    "A history professor with tweed jackets and stacks of books piled up on their desk.",
    "A tattoo artist with a punk rock aesthetic and a portfolio filled with intricate designs.",
    "A delivery driver who listens to podcasts and keeps a journal about the unusual places he’s been.",
    "A dancer in their late teens who practices tirelessly for auditions and competitions.",
    "An aspiring astronaut who spends every free moment reading about space exploration.",
    "A farmer with weathered hands and a big straw hat, tending to fields at dawn.",
    "A nurse who hums softly while taking care of patients during night shifts.",
    "A programmer who works late nights and keeps a whiteboard filled with notes and ideas.",
    "A retired police officer who spends his days woodworking in his garage workshop.",
    "A teenager who loves cosplay and spends weekends designing costumes of their favorite characters.",
    "A librarian who loves cataloging books and secretly writes fantasy novels after work.",
    "A violinist who plays in an orchestra and loses herself in music during every performance.",
    "A surfer with sun-bleached hair who chases waves along the coasts around the world.",
    "A man in his forties who collects antiques and always has a story to tell about his latest find.",
    "A barista who dreams of becoming a photographer and sneaks shots of customers for inspiration.",
    "A carpenter who carves intricate wooden sculptures in his spare time.",
    "A scientist studying marine biology who spends months at sea observing dolphins and whales.",
    "A teenager who runs a successful YouTube channel where they showcase DIY crafts and experiments.",
    "A traveler who journals every adventure, capturing memories in watercolor paintings.",
    "An architect with a passion for designing green, sustainable buildings.",
    "A park ranger who spends her days educating visitors about local wildlife and ecosystems.",
    "A DJ who spends late nights mixing tracks for underground music festivals.",
    "A middle-aged man who collects coins and spends weekends attending collector fairs.",
    "A college student who organizes charity events and volunteers in their free time.",
    "A flight attendant who has visited over fifty countries and documents every trip with a photo album.",
    "An art curator who spends her days sourcing pieces for galleries and art shows.",
    "A mountain climber who trains relentlessly for the next big peak.",
    "A violin repair expert who lovingly restores antique instruments to their former glory.",
    "A young woman who teaches kids to swim and competes in local triathlons.",
    "A middle-aged handyman who always carries a toolbox and is ready to fix anything.",
    "A woman who runs a cat shelter and spends her evenings knitting blankets for her furry friends.",
    "A man who works in a bookstore and recommends obscure novels to every customer.",
    "A baker who specializes in ornate cakes for weddings and celebrations.",
    "A woman who keeps a journal filled with daily haikus inspired by her surroundings.",
    "A teenager with a green thumb, who grows vegetables in their backyard and sells them at a local market.",
    "A competitive chess player who practices strategies for hours on end.",
    "An IT technician who spends weekends building custom computers for his friends.",
    "A young man who organizes local music festivals and plays bass guitar in a band.",
    "A meteorologist who loves storms and never misses the chance to chase a tornado.",
    "A man in his thirties who works as a translator and speaks five languages fluently.",
    "A lifeguard with a whistle around his neck and a deep tan from long days at the beach.",
    "A retired couple who travel across the country in their RV, visiting national parks.",
    "A wildlife photographer who wakes up before dawn to capture animals in their natural habitat.",
    "A quiet cobbler who repairs shoes in a small shop that’s been in the family for generations.",
    "A quirky inventor who designs strange gadgets in their cluttered basement workshop.",
    "A veterinarian who takes care of animals big and small with gentle hands and a calm voice.",
    "An engineer who designs roller coasters and rides at amusement parks.",
    "A young woman who collects vinyl records and hosts listening parties for friends.",
    "A man who volunteers as a firefighter in a small town while working as a mechanic during the day.",
    "An aspiring filmmaker who shoots short films using a handheld camera and local actors.",
    "A mime artist who performs silent routines on busy city streets.",
    "A sailor who loves navigating with the stars and dreams of circumnavigating the globe.",
    "A baker who wakes up at dawn to prepare fresh pastries for the local farmers' market.",
    "A woman who works as a translator for diplomats and thrives on solving communication challenges."
]

ALL_TOPICS = {
    "apples and bananas": ["bananas are superior to apples","apples are superior to bananas"],
    "pineapples going on pizza": ["pineapples should go on pizza", "pineapples should not go on pizza"],
    "purple or orange napkins": ["purple napkins are better than orange napkins","orange napkins are better than purple napkins"],
    "CMU": ["CMU will recruit more students in 2025 than 2024","CMU will recruit less students in 2025 than 2024"],
    "Earth": ["The Earth is not flat","The Earth is flat"],
    "AI Voice Generators": ["there are potential many ethical concerns relating to AI voice generators","AI Voice Generators are superior in the future"]
}